SELECT COUNT(ANIMAL_ID)
FROM ANIMAL_INS

SELECT COUNT(DISTINCT NAME)
FROM ANIMAL_INS

SELECT ANIMAL_TYPE, COUNT(ANIMAL_TYPE) AS count
FROM ANIMAL_INS
GROUP BY ANIMAL_TYPE

SELECT NAME, COUNT(NAME) AS COUNT
FROM ANIMAL_INS
GROUP BY NAME
HAVING COUNT > 1

SELECT HOUR(DATETIME) AS HOUR, COUNT(HOUR(DATETIME))
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME) > 8 AND HOUR(DATETIME) < 20
GROUP BY HOUR
ORDER BY HOUR