# 오랜 기간 보호한 동물(1)

SELECT P.NAME, P.DATETIME
FROM ANIMAL_INS AS P
LEFT JOIN ANIMAL_OUTS AS D
ON P.ANIMAL_ID = D.ANIMAL_ID
WHERE D.ANIMAL_ID IS NULL
ORDER BY P.DATETIME
LIMIT 3

# 오랜 기간 보호한 동물(2)

SELECT D.ANIMAL_ID, D.ANIMAL_TYPE, D.NAME
FROM ANIMAL_INS AS P
RIGHT JOIN ANIMAL_OUTS AS D
ON P.ANIMAL_ID = D.ANIMAL_ID
WHERE SUBSTR(P.SEX_UPON_INTAKE, 1, 1) = "I" AND 
(SUBSTR(D.SEX_UPON_OUTCOME, 1, 1) = "S" OR SUBSTR(D.SEX_UPON_OUTCOME, 1, 1) = "N")
ORDER BY D.ANIMAL_ID