SELECT * 
FROM ANIMAL_INS 
ORDER BY ANIMAL_ID

SELECT MAX(DATETIME) AS 시간
FROM ANIMAL_INS

SELECT MIN(DATETIME) AS 시간
FROM ANIMAL_INS

# eq
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE INTAKE_CONDITION = "Sick"

# not eq
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE INTAKE_CONDITION <> 'Aged'
ORDER BY ANIMAL_ID

SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
ORDER BY ANIMAL_ID

# 정렬 조건 여러개
SELECT ANIMAL_ID, NAME, DATETIME
FROM ANIMAL_INS
ORDER BY NAME, DATETIME DESC

# 상위 하나만 보기
SELECT NAME 
FROM ANIMAL_INS
ORDER BY DATETIME
LIMIT 1