SELECT 
    P.CART_ID
FROM
    (SELECT CART_ID FROM CART_PRODUCTS WHERE SUBSTR(NAME, 1, 2) = "우유") AS MILK
INNER JOIN
    CART_PRODUCTS AS P
ON 
    MILK.CART_ID = P.CART_ID
WHERE SUBSTR(P.NAME, 1, 2) = "요거"